### ISSUE TITLE
Refactor Track Database Fields

### ISSUE THREAD

**Issue by JPDSousa** [JPDSousa/rookit-data-model#36]
Hacktoberfester? :octocat:
------------
Hey Hacktoberfester, if you came across this issue and you like music (and java), you've just found an awesome project to contribute to! Check out the [README](https://github.com/JPDSousa/rookit-data-model) for installation instructions.

If you're not so much into this theme but you would like to contribute to other projects of mine: [search my other Hacktoberfest issues](https://github.com/search?utf8=%E2%9C%93&q=label%3Ahacktoberfest+state%3Aopen+type%3Aissue+author%3AJPDSousa&type=)

Description :mag:
--------
- Remove `DURATION` from Track's `DatabaseField`, as it is inherited from `Playable`.

**Comment by mirkoperillo** [comment]
Hi @JPDSousa I wanna help you on this issue for Hackotoberfest

**Comment by JPDSousa** [comment]
Sure @mirkoperillo ! Thanks a lot!
